pcall(require, "impatient")
require("options")
require("plugins/pack")
require("plugins/telescope")
require("plugins/treesitter")
require("plugins/nvim_tree")
require("plugins/statusline")
require("plugins/whichkey")

vim.cmd("colorscheme dracula")
